language: node_js
node_js: node
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
script:
  - "npm run test"
after_success:
  - "npm run deploy"
